
export interface LLMMessage {
    role: 'system' | 'user' | 'assistant';
    content: string;
}

export interface LLMService {
    generateText(messages: LLMMessage[], systemPrompt?: string): Promise<string>;
}

export class MockLLMService implements LLMService {
    async generateText(messages: LLMMessage[], systemPrompt?: string): Promise<string> {
        const lastUserMessage = messages[messages.length - 1].content.toLowerCase();

        console.log(`[MockLLM] Processing prompt: "${lastUserMessage.substring(0, 50)}..."`);
        await new Promise(resolve => setTimeout(resolve, 800)); // Simulate latency

        // Product Owner Logic
        if (lastUserMessage.includes('refine these requirements')) {
            return `
# Requirements Specification v1.0
## Summary
${lastUserMessage.split('idea:')[1] || 'A new mobile application...'}

## Key Features
1. User Authentication (Login/Signup)
2. Main Dashboard View
3. Search & Filter Capability
4. User Profile Management
5. Settings configuration

## Technical Constraints
- Mobile-first responsive design
- Dark mode support required
`;
        }

        // UX Designer Logic
        if (lastUserMessage.includes('generate design description') || lastUserMessage.includes('ux')) {
            return `
**High-Fidelity Design Spec**
- **Theme**: "Oceanic Depth" (Deep blues and teals)
- **Typography**: Inter (Headings), Roboto (Body)
- **Components**:
  - \`HeroCard\`: Rounded corners, 16px padding, shadow-md
  - \`NavButton\`: Floating action button, bottom right
  - \`DarkToggle\`: Top right corner
`;
        }

        // Backend Logic
        if (lastUserMessage.includes('openapi') || lastUserMessage.includes('api spec')) {
            return `
openapi: 3.0.0
info:
  title: Generated API
  version: 1.0.0
paths:
  /users:
    get:
      summary: List users
  /auth/login:
    post:
      summary: User login
  /items:
    get:
      summary: Search items
`;
        }

        // Frontend Logic
        if (lastUserMessage.includes('react component')) {
            return `
import React from 'react';

export const GeneratedComponent: React.FC = () => {
  return (
    <div className="p-4 bg-gray-900 text-white rounded-lg shadow-md">
      <h2 className="text-xl font-bold mb-4">Dashboard</h2>
      <p>Content generated by AI Agent.</p>
      <button className="bg-blue-500 px-4 py-2 mt-2 rounded">
        Action
      </button>
    </div>
  );
};
`;
        }

        // QA Logic
        if (lastUserMessage.includes('test cases')) {
            return `
- [x] TEST-001: Verify login with valid credentials
- [x] TEST-002: Verify 404 handling on invalid routes
- [x] TEST-003: Check responsiveness on mobile viewport
- [ ] TEST-004: Validate dark mode toggle (Manual check required)
`;
        }

        return "I am a mock AI. passing through generic response.";
    }
}
