
import { BaseAgent } from './base';
import { EventType } from '../core/events';

export class BackendSDEAgent extends BaseAgent {
    constructor(memory: any, eventBus: any, llm: any) {
        super('backend_sde', memory, eventBus, llm);
    }

    initialize() {
        this.eventBus.subscribe(EventType.UX_DESIGN_READY, (event: any) => {
            console.log(`[Backend SDE] UX designs ready. Analyzing for API requirements...`);
            this.startApiDesign();
        });
    }

    protected getRelevantArtifacts(snapshot: any) {
        return {
            ux_design: snapshot.living_documents.ux_design
        };
    }

    async act(): Promise<boolean> {
        const context = this.getContext();

        if (context.my_current_task && context.my_current_task.currently_working_on === 'api_design') {
            console.log('[Backend SDE] Generating API contracts based on UX...');
            await this.finishApiDesign();
            return true;
        }

        return false;
    }

    private startApiDesign() {
        this.memory.updatePhase('development');
        this.memory.updateAgentContext(this.role, {
            currently_working_on: 'api_design',
            next_tasks: ['implement_endpoints']
        });
    }

    private async finishApiDesign() {
        console.log('[Backend SDE] API Design complete. Updating memory.');

        // Artificial delay for visualization
        await new Promise(resolve => setTimeout(resolve, 3000));

        const { AGENT_PROMPTS } = require('../core/prompts');
        const apiSpec = await this.llm.generateText([
            { role: 'system', content: AGENT_PROMPTS.backend_sde },
            { role: 'user', content: 'Generate OpenAPI spec based on the UX design.' }
        ]);

        this.memory.updateDocument('api_contracts', {
            version: '1.0.0',
            summary: 'REST API generated by AI.',
            openapi_spec: apiSpec
        });

        this.memory.updateAgentContext(this.role, {
            currently_working_on: 'idle',
            next_tasks: ['awaiting_frontend_implementation']
        });

        this.eventBus.emit(EventType.API_CONTRACT_DEFINED, this.role, {
            summary: 'API contracts defined and available in memory.'
        });
    }
}
